NSGlobalDomain:KeyRepeat=2
NSGlobalDomain:InitialKeyRepeat=15
com.apple.dock:autohide=1
com.apple.dock:tilesize=55
NSGlobalDomain:com.apple.trackpad.scaling=1.5

# Mission Control shortcuts
symbolic:79:enabled=1
symbolic:79:params=65535,123,10354688
symbolic:80:enabled=0
symbolic:80:params=65535,123,8781824
symbolic:81:enabled=1
symbolic:81:params=65535,124,10354688
symbolic:82:enabled=0
symbolic:82:params=65535,124,8781824
